
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Sat Aug 01 18:57:05 EDT 1998
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int QUESTION = 31;
  static final int EOF = 0;
  static final int PAPER = 18;
  static final int LINE = 23;
  static final int LBRACKET = 12;
  static final int DIVIDE = 5;
  static final int NUMBER = 25;
  static final int error = 1;
  static final int VALUE = 27;
  static final int UMINUS = 6;
  static final int MINUS = 3;
  static final int COMMAND = 24;
  static final int COMMANDNAME = 32;
  static final int TIMES = 4;
  static final int LPAREN = 7;
  static final int RPAREN = 8;
  static final int ALIAS = 9;
  static final int INTEGER = 29;
  static final int LOAD = 28;
  static final int PEN = 19;
  static final int ESCAPE = 26;
  static final int ANTIALIAS = 10;
  static final int LBRACE = 14;
  static final int PLUS = 2;
  static final int RBRACE = 13;
  static final int FOREVER = 22;
  static final int RETURN = 20;
  static final int SET = 17;
  static final int RBRACKET = 11;
  static final int NAME = 30;
  static final int REPEAT = 21;
  static final int LBLOCK = 16;
  static final int RBLOCK = 15;
}

